steps:
- name: 'python'
  entrypoint: 'pip'
  args: ['install', '-r', 'requirements.txt']
  
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'main', 
         '--runtime', 'python39',
         '--trigger-topic','adaptive-pipeline-workflow-topic'] 
